module com.epa.erb {
	requires java.base;
	requires javafx.fxml;
	requires javafx.base;
	requires java.desktop;
	requires jdk.compiler;
	requires jdk.jsobject;
	requires javafx.swing;
	requires org.apache.poi.poi;
	requires org.apache.xmlbeans;
	requires org.apache.commons.io;
	requires org.controlsfx.controls;
	requires org.apache.poi.ooxml.schemas;
	requires transitive java.xml;
	requires transitive javafx.web;
	requires transitive java.logging;
	requires transitive javafx.graphics;
	requires transitive javafx.controls;
	requires transitive org.apache.poi.ooxml;
	opens com.epa.erb to javafx.fxml;
	opens com.epa.erb.goal to javafx.fxml;
	opens com.epa.erb.excel to javafx.fxml;
	opens com.epa.erb.forms to javafx.fxml;
	opens com.epa.erb.print to javafx.fxml;
	opens com.epa.erb.project to javafx.fxml;
	opens com.epa.erb.noteboard to javafx.fxml;
	opens com.epa.erb.indicators to javafx.fxml;
	opens com.epa.erb.finalReport to javafx.fxml;
	opens com.epa.erb.wordcloud to javafx.fxml, javafx.base;
	opens com.epa.erb.engagement_action to javafx.fxml, javafx.base;
	exports com.epa.erb;
	exports com.epa.erb.goal;
	exports com.epa.erb.excel;
	exports com.epa.erb.forms;
	exports com.epa.erb.print;
	exports com.epa.erb.project;
	exports com.epa.erb.utility;
	exports com.epa.erb.wordcloud;
	exports com.epa.erb.noteboard;
	exports com.epa.erb.indicators;
	exports com.epa.erb.finalReport;
	exports com.epa.erb.engagement_action;
}