/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package erb;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application{
    
	public String getGreeting() {
        return "Launching ERB";
    }

    public static void main(String[] args) {
       Application.launch(args);
    }

	@Override
	public void start(Stage primaryStage) throws Exception {
		System.out.println(new App().getGreeting());		
	}
	
}
